### ISSUE TITLE
Error from stable-diffusion-webui-eyemask\install.py on server startup

### ISSUE THREAD

**Issue by Gerkinfeltser** [ilian6806/stable-diffusion-webui-eyemask#15]
Using Vladmandic webui, I am getting errors on install.py on startup as reported in setup.log.
Looking at the other issue #8 I modified the eyemask's install.py from
`git_clone("https://github.com/isl-org/MiDaS.git", "repositories/midaS", "midaS")` to `git_clone("https://github.com/isl-org/MiDaS.git", "repositories/MiDaS", "MiDaS")` thinking maybe it was due to the differences in case of the dir in question issue but this didn't help. I also removed (actually renamed) the MiDaS dir & restarted the server but this didn't help either.

This is the relevant section of the setup.log:

2023-05-27 21:52:40,404 | ERROR | C:\ai\automatic\installer.py | Error running extension installer: C:\ai\automatic\extensions\stable-diffusion-webui-eyemask\install.py
2023-05-27 21:52:40,407 | DEBUG | C:\ai\automatic\installer.py | 
Error in sys.excepthook:

Traceback (most recent call last):

  File "C:\ai\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook

    Traceback.from_exception(

  File "C:\ai\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception

    return cls(

  File "C:\ai\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__

    for suppress_entity in suppress:

TypeError: 'module' object is not iterable

Original exception was:

Traceback (most recent call last):

  File "C:\ai\automatic\extensions\stable-diffusion-webui-eyemask\install.py", line 6, in <module>

    from modules.sd_models import model_hash

  File "C:\ai\automatic\modules\sd_models.py", line 15, in <module>

    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config

  File "C:\ai\automatic\modules\shared.py", line 196, in <module>

    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"

  File "C:\ai\automatic\modules\shared.py", line 194, in list_checkpoint_tiles

    return modules.sd_models.checkpoint_tiles()

AttributeError: module 'modules' has no attribute 'sd_models'

.... clipped as there wasn't anything relevent ...

2023-05-27 21:52:57,439 | WARNING | C:\ai\automatic\installer.py | Setup complete with errors: 1
2023-05-27 21:52:57,441 | WARNING | C:\ai\automatic\installer.py | See log file for more details: setup.log

**Comment by ilian6806** [comment]
Hello @Gerkinfeltser!
This extension is for AUTOMATIC1111 web ui. I have not tested it with other forks.

**Comment by Gerkinfeltser** [comment]
Understood! Thank you for your reply!
