### ISSUE TITLE
FileNotFoundError:  [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by Mastergod666** [ilian6806/stable-diffusion-webui-eyemask#19]
Dlib installed and also cmake with PATH enabled for all users + visual studio build tools (no errors in the console)
clean installation of sdwebui (automatic1111)
eye mask prompt: "yellow eyes"

"Running DDIM Sampling with 40 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████| 40/40 [00:27<00:00,  1.43it/s]
Processing 1 / 1.00%|██████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  1.62it/s]
Running DDIM Sampling with 8 timesteps
Decoding image: 100%|████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.17s/it]
Total progress: 48it [00:36,  1.30it/s]
Traceback (most recent call last):s/it]
  File "C:\Users\zanichelliludovico\Desktop\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\zanichelliludovico\Desktop\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\zanichelliludovico\Desktop\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\zanichelliludovico\Desktop\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\zanichelliludovico\Desktop\SD\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Program Files\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Program Files\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Program Files\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZANICH~1\\AppData\\Local\\Temp\\2\\gradio\\tmpob30uruk.png'"

**Comment by ilian6806** [comment]
This error seems to be not related to the extension

**Comment by roro19844** [comment]
I get this error too on my 2nd side pc but no issues on my main computer. Couldn't really pinpoint wat is doing that but the plugin is still working fine, kinda can ignore this.

**Comment by JokerGT** [comment]
same issue here on windows with no other extension installed. latest automatic1111 dev version

**Comment by JokerGT** [comment]
i just found a solution for this:

just create the missing "gradio" folder. 

eg @Mastergod666 C:\Users\ZANICH~1\AppData\Local\Temp\2\gradio

makedir C:\Users\ZANICH~1\AppData\Local\Temp\2\gradio 

and it should work
