### ISSUE TITLE
Get Frontal Face Detector Error

### ISSUE THREAD

**Issue by mageofthesands** [ilian6806/stable-diffusion-webui-eyemask#21]
It took awhile for me to get Eyemask installed, but now it just won't run.  It's like I need a file for it to load, but I cannot figure out where to get said file.  I'm on version:  •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: 9ee2133245.  I'm running an AMD 6750 XT on Windows 10 using https://github.com/lshqqytiger/stable-diffusion-webui-directml.

`Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████████████████▋  | 44/45 [06:17<00:13, 13.10s/it]
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 110, in on_generate_mask_click
    mask, mask_success = self.eye_mask_core.generate_mask(input_image, em_mask_type)
  File "H:\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 262, in generate_mask
    return mask_generator.get_eyes_mask_dlib(init_image, em_mask_padding, em_mask_padding_in_px)
  File "H:\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 52, in get_eyes_mask_dlib
    faces, gray = _get_detected_faces_dlib(init_image)
  File "H:\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 35, in _get_detected_faces_dlib
    face_detector = dlib.get_frontal_face_detector()
AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'`

**Comment by ilian6806** [comment]
It looks like dlib module is another version or there is some naming collision with some other lib...

**Comment by mageofthesands** [comment]
At this point, I have no idea what to install to get this to work.  As far as I am aware of, I installed dlib.
