### ISSUE TITLE
Error installing extension on Vladmandics SD.NEXT webui (an automatic111 fork)

### ISSUE THREAD

**Issue by Alverik** [ilian6806/stable-diffusion-webui-eyemask#25]
I really like this extension, but I switched to Vladmandics SD.NEXT (at least on my hardware it's more efficient/faster than automatic1111), Any chance we can get a version that works on that fork?

This is the error I get when I try to install it...

```
Error running extension installer: D:\Program Files\Vlad1111\extensions\stable-diffusion-webui-eyemask\install.py
22:20:04-849034 DEBUG
                         Error in sys.excepthook:
                         Traceback (most recent call last):
                           File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 103, in
                         excepthook
                             Traceback.from_exception(
                           File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 346, in
                         from_exception
                             return cls(
                           File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 280, in
                         __init__
                             for suppress_entity in suppress:
                         TypeError: 'module' object is not iterable

                         Original exception was:
                         Traceback (most recent call last):
                           File "D:\Program Files\Vlad1111\extensions\stable-diffusion-webui-eyemask\install.py", line
                         6, in <module>
                             from modules.sd_models import model_hash
                           File "D:\Program Files\Vlad1111\modules\sd_models.py", line 18, in <module>
                             from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae,
                         sd_disable_initialization, errors, hashes, sd_models_config
                           File "D:\Program Files\Vlad1111\modules\shared.py", line 234, in <module>
                             default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else
                         "model.ckpt"
                           File "D:\Program Files\Vlad1111\modules\shared.py", line 232, in list_checkpoint_tiles
                             return modules.sd_models.checkpoint_tiles()
                         AttributeError: module 'modules' has no attribute 'sd_models'


Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\Program Files\Vlad1111\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\Program Files\Vlad1111\extensions\stable-diffusion-webui-eyemask\install.py", line 6, in <module>
    from modules.sd_models import model_hash
  File "D:\Program Files\Vlad1111\modules\sd_models.py", line 18, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "D:\Program Files\Vlad1111\modules\shared.py", line 234, in <module>
    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"
  File "D:\Program Files\Vlad1111\modules\shared.py", line 232, in list_checkpoint_tiles
    return modules.sd_models.checkpoint_tiles()
AttributeError: module 'modules' has no attribute 'sd_models'
```

**Comment by ilian6806** [comment]
This extension is for AUTOMATIC1111 web ui. I have not tested it with other forks. Unfortunately, I don't have much time lately... I will leave this issue open if someone can check this out...
