### ISSUE TITLE
Does not install on A1111 due to pytorch depreciation

### ISSUE THREAD

**Issue by duaneking** [ilian6806/stable-diffusion-webui-eyemask#26]
Does not run or install in A1111.

```
*** Error running install.py for extension C:\Users\User\Workspace\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask.█████████████████████████████████████| 20/20 [00:11<00:00,  1.77it/s]
*** Command: "C:\Users\User\Workspace\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\User\Workspace\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\install.py"
*** Error code: 1
*** stdout: no module 'xformers'. Processing without...
*** no module 'xformers'. Processing without...
*** No module 'xformers'. Proceeding without it.
***
*** stderr: C:\Users\User\Workspace\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** Traceback (most recent call last):
***   File "C:\Users\User\Workspace\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\install.py", line 6, in <module>
***     from modules.sd_models import model_hash
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_models.py", line 17, in <module>
***     from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl, cache, extra_networks, processing, lowvram, sd_hijack
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_vae.py", line 5, in <module>
***     from modules import paths, shared, devices, script_callbacks, sd_models, extra_networks, lowvram, sd_hijack, hashes
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_hijack.py", line 5, in <module>
***     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 13, in <module>
***     from modules.hypernetworks import hypernetwork
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\hypernetworks\hypernetwork.py", line 13, in <module>
***     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_samplers.py", line 59, in <module>
***     set_samplers()
***   File "C:\Users\User\Workspace\stable-diffusion-webui\modules\sd_samplers.py", line 44, in set_samplers
***     samplers_hidden = set(shared.opts.hide_samplers)
*** AttributeError: 'NoneType' object has no attribute 'hide_samplers'
```

This is clearly a code issue as its calling things that do not exist no doubt due to api updates.

**Comment by ilian6806** [comment]
Fixed this.
