### ISSUE TITLE
Startup error tried rec on previous problem thread didnt work

### ISSUE THREAD

**Issue by HinaHyugaHime** [ilian6806/stable-diffusion-webui-eyemask#30]
/home/ellia/stable-diffusion-webui/venv/lib/python3.11/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension /home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask.
*** Command: "/home/ellia/stable-diffusion-webui/venv/bin/python3" "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/install.py"
*** Error code: 1
*** stdout: no module 'xformers'. Processing without...
*** no module 'xformers'. Processing without...
*** No module 'xformers'. Proceeding without it.
*** 
*** stderr: /home/ellia/stable-diffusion-webui/venv/lib/python3.11/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** Traceback (most recent call last):
***   File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/install.py", line 6, in <module>
***     from modules.sd_models import model_hash
***   File "/home/ellia/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
***     from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl, cache, extra_networks, processing, lowvram, sd_hijack
***   File "/home/ellia/stable-diffusion-webui/modules/sd_vae.py", line 5, in <module>
***     from modules import paths, shared, devices, script_callbacks, sd_models, extra_networks, lowvram, sd_hijack, hashes
***   File "/home/ellia/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
***     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
***   File "/home/ellia/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
***     from modules.hypernetworks import hypernetwork
***   File "/home/ellia/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 13, in <module>
***     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
***   File "/home/ellia/stable-diffusion-webui/modules/sd_samplers.py", line 59, in <module>
***     set_samplers()
***   File "/home/ellia/stable-diffusion-webui/modules/sd_samplers.py", line 44, in set_samplers
***     samplers_hidden = set(shared.opts.hide_samplers)
***                           ^^^^^^^^^^^^^^^^^^^^^^^^^
*** AttributeError: 'NoneType' object has no attribute 'hide_samplers'
Launching Web UI with arguments: --autolaunch
[-] ADetailer initialized. version: 23.11.1, num models: 9
*** Error loading script: em_api.py
    Traceback (most recent call last):
      File "/home/ellia/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ellia/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/em_api.py", line 16, in <module>
        from eyemask.api import EyeMaskApi
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/api/__init__.py", line 3, in <module>
        from . api import EyeMaskApi
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/api/api.py", line 8, in <module>
        from .. import script as eye_mask_script
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/mask_generator.py", line 10, in <module>
        from .modules import depthmap
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/modules/depthmap.py", line 11, in <module>
        from repositories.midas.midas.dpt_depth import DPTDepthModel
    ModuleNotFoundError: No module named 'repositories.midas'

---
*** Error loading script: em_script.py
    Traceback (most recent call last):
      File "/home/ellia/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ellia/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/em_script.py", line 15, in <module>
        from eyemask import constants, ui, script as eye_mask_script
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/ui.py", line 8, in <module>
        from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/mask_generator.py", line 10, in <module>
        from .modules import depthmap
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/modules/depthmap.py", line 11, in <module>
        from repositories.midas.midas.dpt_depth import DPTDepthModel
    ModuleNotFoundError: No module named 'repositories.midas'

---
*** Error loading script: em_script_embedded.py
    Traceback (most recent call last):
      File "/home/ellia/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ellia/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/em_script_embedded.py", line 15, in <module>
        from eyemask import constants, ui, script_embedded as eye_mask_script
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/ui.py", line 8, in <module>
        from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/mask_generator.py", line 10, in <module>
        from .modules import depthmap
      File "/home/ellia/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/modules/depthmap.py", line 11, in <module>
        from repositories.midas.midas.dpt_depth import DPTDepthModel
    ModuleNotFoundError: No module named 'repositories.midas'

---

**Comment by HinaHyugaHime** [comment]
as for the install.py error it error's at import os

**Comment by ilian6806** [comment]
I fixed this with the last commit.
