### ISSUE TITLE
Doesn't install dependencies

### ISSUE THREAD

**Issue by baaoh** [ilian6806/stable-diffusion-webui-eyemask#8]
Hi!

Would like to try your extension, but the dependencies and requirements don't auto-install into the web-ui venv, so had to do it manually.

then I had a problem with
ModuleNotFoundError: No module named 'repositories.midas'

tried both A1111 and Vladmandic webui

`22:35:04-005239 ERROR    Module load:
                         F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\em_api.py:
                         ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\StableDiffusion\automatic\modules\script_loading.py:10 in load_module                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 5 frames hidden ...                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py:10 in      │
│ <module>                                                                                                            │
│                                                                                                                     │
│     9 from .utils import expand_polygon, calculate_distance                                                         │
│ >  10 from .modules import depthmap                                                                                 │
│    11                                                                                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py:11 in    │
│ <module>                                                                                                            │
│                                                                                                                     │
│    10 from torchvision.transforms import Compose                                                                    │
│ >  11 from repositories.midas.midas.dpt_depth import DPTDepthModel                                                  │
│    12 from repositories.midas.midas.midas_net import MidasNet                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'repositories.midas'
22:35:04-063290 ERROR    Module load:
                         F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\em_script.py:
                         ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\StableDiffusion\automatic\modules\script_loading.py:10 in load_module                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py:10 in      │
│ <module>                                                                                                            │
│                                                                                                                     │
│     9 from .utils import expand_polygon, calculate_distance                                                         │
│ >  10 from .modules import depthmap                                                                                 │
│    11                                                                                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py:11 in    │
│ <module>                                                                                                            │
│                                                                                                                     │
│    10 from torchvision.transforms import Compose                                                                    │
│ >  11 from repositories.midas.midas.dpt_depth import DPTDepthModel                                                  │
│    12 from repositories.midas.midas.midas_net import MidasNet                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'repositories.midas'
22:35:04-092839 ERROR    Module load:
                         F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\em_script_embed
                         ded.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\StableDiffusion\automatic\modules\script_loading.py:10 in load_module                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py:10 in      │
│ <module>                                                                                                            │
│                                                                                                                     │
│     9 from .utils import expand_polygon, calculate_distance                                                         │
│ >  10 from .modules import depthmap                                                                                 │
│    11                                                                                                               │
│                                                                                                                     │
│ F:\StableDiffusion\automatic\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py:11 in    │
│ <module>                                                                                                            │
│                                                                                                                     │
│    10 from torchvision.transforms import Compose                                                                    │
│ >  11 from repositories.midas.midas.dpt_depth import DPTDepthModel                                                  │
│    12 from repositories.midas.midas.midas_net import MidasNet                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'repositories.midas'`

**Comment by ilian6806** [comment]
Is your SD at latest version? You can check your /repositories directory. If there is no midas directory, you must checkout it from https://github.com/isl-org/MiDaS.git.

git_clone("https://github.com/isl-org/MiDaS.git", "repositories/midas", "midas")

This row install it for you. It`s in install.py.

**Comment by baaoh** [comment]
Got it, installed midas manually, updated A1111 to latest commit, but still dealing with this

```
Error loading script: em_api.py
Traceback (most recent call last):
  File "F:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_api.py", line 16, in <module>
    from eyemask.api import EyeMaskApi
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\__init__.py", line 3, in <module>
    from . api import EyeMaskApi
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\api.py", line 8, in <module>
    from .. import script as eye_mask_script
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 10, in <module>
    from .modules import depthmap
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

Error loading script: em_script.py
Traceback (most recent call last):
  File "F:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script.py", line 15, in <module>
    from eyemask import constants, ui, script as eye_mask_script
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 10, in <module>
    from .modules import depthmap
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

Error loading script: em_script_embedded.py
Traceback (most recent call last):
  File "F:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script_embedded.py", line 15, in <module>
    from eyemask import constants, ui, script_embedded as eye_mask_script
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 10, in <module>
    from .modules import depthmap
  File "F:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\modules\depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "F:\StableDiffusion\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'
```

**Comment by ilian6806** [comment]
It looks like some dependency problem again... Do you install midas in /repositories or with pip?

**Comment by baaoh** [comment]
i did it with cmd within venv, also did pip install of dependencies for midas

**Comment by ilian6806** [comment]
I think it will be better to cd in /repositories and execute 
```
git clone https://github.com/isl-org/MiDaS.git
```

**Comment by TwistedTexan4Life** [comment]
> I think it will be better to cd in /repositories and execute
> 
> ```
> git clone https://github.com/isl-org/MiDaS.git
> ```

I'm having the exact same issue as the original poster but none of this has fixed these errors.  I've installed CMake, i've run the git clone and have the MiDaS dircectory in repositories.  I've checked and SD is up to date.  Not sure if I missed something or installed something wrong, any ideas.

`Error loading script: em_api.py
Traceback (most recent call last):
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\em_api.py", line 16, in <module>
    from eyemask.api import EyeMaskApi
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\api\__init__.py", line 3, in <module>
    from . api import EyeMaskApi
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\api\api.py", line 8, in <module>
    from .. import script as eye_mask_script
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

Error loading script: em_script.py
Traceback (most recent call last):
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\em_script.py", line 15, in <module>
    from eyemask import constants, ui, script as eye_mask_script
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

Error loading script: em_script_embedded.py
Traceback (most recent call last):
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "S:\AI Graphics Generation\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\em_script_embedded.py", line 15, in <module>
    from eyemask import constants, ui, script_embedded as eye_mask_script
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "S:\AI Graphics Generation\stable-diffusion-webui\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'`
